# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: Silvanion.Saldo
PackageVersion: 1.6.4
DefaultLocale: pl-PL
ManifestType: version
ManifestVersion: 1.6.0
